In [7]:
#Warm Up - reverse this list 

my_list = [0,1,2,3,4,5,6,7,8,9]

reversed_list = my_list[::-1]
reversed_list

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [8]:
#then use list comprehension to halve the values in the list

halved_my_list= [number/2 for number in reversed_list]
print(halved_my_list)

[4.5, 4.0, 3.5, 3.0, 2.5, 2.0, 1.5, 1.0, 0.5, 0.0]


In [15]:
#VECTORS


import numpy as np
v = np.array([[1],[2],[3]])
v

array([[1],
       [2],
       [3]])

In [16]:
v.shape

(3, 1)

In [13]:
#MATRICES

M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
M.shape

(3, 3)

In [38]:
#SCALAR - number that can be applied to all individual values in an array

#scalar
x=3.5


#define vector, v already defined
v2 = np.array([[-1],[-2],[-3]])

#zipping to arrays together
new_matrix=zip(v,v2)
#shows the location in memory
new_matrix

In [71]:
#cast to list to actually view data
#list comprised of arrays
new_matrix=list(zip(v,v2))
new_matrix

[(array([1]), array([-1])),
 (array([2]), array([-2])),
 (array([3]), array([-3]))]

In [21]:
type(new_matrix)

list

In [22]:
print(v.T) #v transposed
print(v)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [25]:
#sum of 1*1 + 2*2 + 3*3
np.dot(v.T, v)

array([[14]])

In [28]:
#Think directionality - convert that into vectors

north = np.array([0,1])
east = np.array([1,0])
south = np.array([0,-1])
west = np.array([-1,0])

#to what degree are the two directions the same
print(np.dot(north, south)) #the have 1 in common

print(np.dot(north, east)) #0, they have nothing in common

-1
0


In [33]:
#create an example

a = np.array([5, 6, 7])
b = np.array([-5, -6, -7])

print(np.dot(a, b))

-110


In [39]:
print(v)
print(v2)

#this example does not work with default axis setting
np.cross(v, v2, axisa=0, axisb=0)

#returns all 0s because the two arrays are entirely opposite

[[1]
 [2]
 [3]]
[[-1]
 [-2]
 [-3]]


array([[0, 0, 0]])

Orthogonality - two vectors are orthogonal is they are perpendicular

the dot product is 0 or the identity matrix

(two dollar signs) A \cdot A^T = I (two dollar signs)

$$ A \cdot A^T = I $$

In [42]:
#identity matrix, 1s on the diagonal and other values are 0
M = np.array([[1,0,0],
            [0,1,0],
            [0,0,1]])
M

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [43]:
# a test for the orthogonality is if the matrix and its transpose 
#equal the identity matrix

np.dot(M, M.T)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [50]:
A = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(A)

np.dot(A, A.T)

#not orthoginal

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [49]:
B = np.array([[1,2,3],
             [2,3,1],
             [3,1,2]])
print(B)

np.dot(B, B.T)

#not orthoginal

[[1 2 3]
 [2 3 1]
 [3 1 2]]


array([[14, 11, 11],
       [11, 14, 11],
       [11, 11, 14]])

In [ ]:
Error Handling

# try except else finally for error handling

In [69]:
def countdown(n):
    
    #first print n
    print(n)
    
    #count backward from n until we get to 0
    if n>0:
        
        #perform action
        countdown(n-1)
        
    else:
        
        #stopping condition, terminates recursion
        return

In [70]:
countdown(2)

2
1
0


In [ ]:
#play around with moving the print statement to understand 